sudo: required
services:
    - docker

before_install:
    - docker build -t shpraveen/react-test -f ./client/Dockerfile.dev

script:
    - docker run shpraveen/react-test npm test -- --coverage

after_success:
    - docker build -t shpraveen/multi-client ./client
    - docker build -t shpraveen/multi-nginx ./nginx
    - docker build -t shpraveen/multi-server ./server
    - docker build -t shpraveen/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push shpraveen/multi-client 
    - docker push shpraveen/multi-nginx
    - docker push shpraveen/multi-server
    - docker push shpraveen/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-302134621
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY